Function Format-SQLogs {
	[CmdLetBinding(SupportsShouldProcess=$True)]
	param(
		#Specify directory where the logs was saved using Get-SQLogs
			$Source

		,#Generate a detailed report in excel
			[switch]$ReportEx
	)
	
	$ErrorActionPreference = "Stop";
	$IsVerbose = $PSCmdlet.MyInvocation.BoundParameters["Verbose"].IsPresent
	

	#Defining some functions and configurations for script...
		
	$GMV = GetGMV
	$CmdLetBaseFolder = "$($GMV.CMDLETSIDR)\Format-SQLog\libs"
	

	
		
	<#
		.SYNOPSIS 
			Formats and analyze logs generated by Get-SQLogs cmdlet!
			
		.DESCRIPTION
			This cmdlet allows user formats and generate many data absed on collect information by SQLLogs.

	#>
}	

